[package]
name = "banded-matrix-solver"
version = "0.1.0"
edition = "2024"

[lib]
name = "banded_matrix_solver"
path = "src/lib.rs"

[dependencies]
rayon = "1.8"
approx = "0.5"
ndarray = "0.5"
once_cell = "1.10"
